import type { Metadata } from 'next';
import './globals.css';
import { NotificationManager } from '../components/NotificationManager';

export const metadata: Metadata = {
    title: 'My New App',
    description: 'Generated by Onlook',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" data-oid="0-ht7f4">
            <body className="" data-oid="u_10dkq">
                {children}
                <NotificationManager data-oid="lknn_p6" />
            </body>
        </html>
    );
}
