import type { Metadata } from 'next';
import './globals.css';
import { NotificationManager } from '../components/NotificationManager';

export const metadata: Metadata = {
    title: 'My New App',
    description: 'Generated by Onlook',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" data-oid="1rcqw8v">
            <body className="" data-oid="5pabqc5">
                {children}
                <NotificationManager data-oid="q4tiucv" />
            </body>
        </html>
    );
}
